# Generated by Django 5.1.1 on 2024-09-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Айди')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': ('Рубрика',),
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
